//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SNIESWebApplication.Recursos.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad benefica.
        /// </summary>
        public static string ActividadBeneficiar {
            get {
                return ResourceManager.GetString("ActividadBeneficiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad Cultural.
        /// </summary>
        public static string ActividadCultural {
            get {
                return ResourceManager.GetString("ActividadCultural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad de Rec. Humano.
        /// </summary>
        public static string ActividadRecHumano {
            get {
                return ResourceManager.GetString("ActividadRecHumano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apoyo a estudiante.
        /// </summary>
        public static string ApoyoEstudiante {
            get {
                return ResourceManager.GetString("ApoyoEstudiante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area Trabajo Proyecto Extencion.
        /// </summary>
        public static string AreaTrabajoProyectoExtencion {
            get {
                return ResourceManager.GetString("AreaTrabajoProyectoExtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area Trabajo Servicio Extension.
        /// </summary>
        public static string AreaTrabajoServicioExtension {
            get {
                return ResourceManager.GetString("AreaTrabajoServicioExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avtividad de Bienestar.
        /// </summary>
        public static string AvtividadBienEstar {
            get {
                return ResourceManager.GetString("AvtividadBienEstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienestar.
        /// </summary>
        public static string BienEstar {
            get {
                return ResourceManager.GetString("BienEstar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacitacion de Docente.
        /// </summary>
        public static string CapacitacionDocente {
            get {
                return ResourceManager.GetString("CapacitacionDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga plantilla.
        /// </summary>
        public static string CargarPlantilla {
            get {
                return ResourceManager.GetString("CargarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargue el documento excel.
        /// </summary>
        public static string CargueDocumentoExcel {
            get {
                return ResourceManager.GetString("CargueDocumentoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciclo Vital Proyecto Extencion.
        /// </summary>
        public static string CicloVitalProyectoExtencion {
            get {
                return ResourceManager.GetString("CicloVitalProyectoExtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciclo Vital Servicio Extension.
        /// </summary>
        public static string CicloVitalServicioExtension {
            get {
                return ResourceManager.GetString("CicloVitalServicioExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultaria.
        /// </summary>
        public static string Consultaria {
            get {
                return ResourceManager.GetString("Consultaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato de Docente.
        /// </summary>
        public static string ContratoDocente {
            get {
                return ResourceManager.GetString("ContratoDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convenio Internacional.
        /// </summary>
        public static string ConvenioInternacional {
            get {
                return ResourceManager.GetString("ConvenioInternacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convenio Internacional Institucion.
        /// </summary>
        public static string ConvenioInternacionalInstitucion {
            get {
                return ResourceManager.GetString("ConvenioInternacionalInstitucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nuevo.
        /// </summary>
        public static string CrearNuevo {
            get {
                return ResourceManager.GetString("CrearNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cupo.
        /// </summary>
        public static string Cupo {
            get {
                return ResourceManager.GetString("Cupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar reporte en Excel.
        /// </summary>
        public static string DescargarReporteExcel {
            get {
                return ResourceManager.GetString("DescargarReporteExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles.
        /// </summary>
        public static string Detalles {
            get {
                return ResourceManager.GetString("Detalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Docente.
        /// </summary>
        public static string Docente {
            get {
                return ResourceManager.GetString("Docente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Docente Educacion Continua.
        /// </summary>
        public static string DocenteEducacionContinua {
            get {
                return ResourceManager.GetString("DocenteEducacionContinua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Educacion Continua.
        /// </summary>
        public static string EducacionContinua {
            get {
                return ResourceManager.GetString("EducacionContinua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta seguro que desea eliminar este registro?.
        /// </summary>
        public static string EliminarConfirmar {
            get {
                return ResourceManager.GetString("EliminarConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad Nacional Proyecto Extencion.
        /// </summary>
        public static string EntidadNacionalProyectoExtencion {
            get {
                return ResourceManager.GetString("EntidadNacionalProyectoExtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entidad Nacional Servicio Extension.
        /// </summary>
        public static string EntidadNacionalServicioExtension {
            get {
                return ResourceManager.GetString("EntidadNacionalServicioExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estudiante de articulacion.
        /// </summary>
        public static string EstudianteArticulacion {
            get {
                return ResourceManager.GetString("EstudianteArticulacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuente Internacional Proyecto Extencion.
        /// </summary>
        public static string FuenteInternacionalProyectoExtencion {
            get {
                return ResourceManager.GetString("FuenteInternacionalProyectoExtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuente Internacional Servicio Extension.
        /// </summary>
        public static string FuenteInternacionalServicioExtension {
            get {
                return ResourceManager.GetString("FuenteInternacionalServicioExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuente Nacional Servicio Extension.
        /// </summary>
        public static string FuenteNacionalServicioExtension {
            get {
                return ResourceManager.GetString("FuenteNacionalServicioExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Guardar {
            get {
                return ResourceManager.GetString("Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscrito.
        /// </summary>
        public static string Inscrito {
            get {
                return ResourceManager.GetString("Inscrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscrito por programa.
        /// </summary>
        public static string InscritoPrograma {
            get {
                return ResourceManager.GetString("InscritoPrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movilidad Administrativo Colombia Internacionalizacion.
        /// </summary>
        public static string MovilidadAdministrativoColombiaInternacionalizacion {
            get {
                return ResourceManager.GetString("MovilidadAdministrativoColombiaInternacionalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movilidad Administrativo Exterior Internacionalizacion.
        /// </summary>
        public static string MovilidadAdministrativoExteriorInternacionalizacion {
            get {
                return ResourceManager.GetString("MovilidadAdministrativoExteriorInternacionalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movilidad Docente Exterior Colombia Internacionalizacion.
        /// </summary>
        public static string MovilidadDocenteExteriorColombiaInternacionalizacion {
            get {
                return ResourceManager.GetString("MovilidadDocenteExteriorColombiaInternacionalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Movilidad Docente Exterior Internacionalizacion.
        /// </summary>
        public static string MovilidadDocenteExteriorInternacionalizacion {
            get {
                return ResourceManager.GetString("MovilidadDocenteExteriorInternacionalizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otra Entidad Proyecto Extencion.
        /// </summary>
        public static string OtraEntidadProyectoExtencion {
            get {
                return ResourceManager.GetString("OtraEntidadProyectoExtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otra Entidad Servicio Extension.
        /// </summary>
        public static string OtraEntidadServicioExtension {
            get {
                return ResourceManager.GetString("OtraEntidadServicioExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Participante.
        /// </summary>
        public static string Participante {
            get {
                return ResourceManager.GetString("Participante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poblacion Condicional Servicio Extension.
        /// </summary>
        public static string PoblacionCondicionalServicioExtension {
            get {
                return ResourceManager.GetString("PoblacionCondicionalServicioExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rec. Humano Consultoria.
        /// </summary>
        public static string RecHumanoConsultoria {
            get {
                return ResourceManager.GetString("RecHumanoConsultoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rec. Humano Cultural.
        /// </summary>
        public static string RecHumanoCultural {
            get {
                return ResourceManager.GetString("RecHumanoCultural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio de Extension.
        /// </summary>
        public static string ServicioExtension {
            get {
                return ResourceManager.GetString("ServicioExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a la lista.
        /// </summary>
        public static string VolverLista {
            get {
                return ResourceManager.GetString("VolverLista", resourceCulture);
            }
        }
    }
}
