//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SNIESWebApplication.Models.StoredProcedure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SAINTdbSp : DbContext
    {
        public SAINTdbSp()
            : base("name=SAINTdbSp")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SNIES_Admitidos_Posg_Result> SNIES_Admitidos_Posg(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNIES_Admitidos_Posg_Result>("SNIES_Admitidos_Posg", periodoParameter);
        }
    
        public virtual ObjectResult<SNIES_Admitidos_Preg_Result> SNIES_Admitidos_Preg(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNIES_Admitidos_Preg_Result>("SNIES_Admitidos_Preg", periodoParameter);
        }
    
        public virtual ObjectResult<SNIES_Inscritos_Posg_Result> SNIES_Inscritos_Posg(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNIES_Inscritos_Posg_Result>("SNIES_Inscritos_Posg", periodoParameter);
        }
    
        public virtual ObjectResult<SNIES_Inscritos_Posg_ConPrograma_Result> SNIES_Inscritos_Posg_ConPrograma(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNIES_Inscritos_Posg_ConPrograma_Result>("SNIES_Inscritos_Posg_ConPrograma", periodoParameter);
        }
    
        public virtual ObjectResult<SNIES_Inscritos_Preg_Result> SNIES_Inscritos_Preg(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNIES_Inscritos_Preg_Result>("SNIES_Inscritos_Preg", periodoParameter);
        }
    
        public virtual ObjectResult<SNIES_Inscritos_Preg_ConPrograma_Result> SNIES_Inscritos_Preg_ConPrograma(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNIES_Inscritos_Preg_ConPrograma_Result>("SNIES_Inscritos_Preg_ConPrograma", periodoParameter);
        }
    
        public virtual ObjectResult<SNIES_Matriculados_Posg_Result> SNIES_Matriculados_Posg(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNIES_Matriculados_Posg_Result>("SNIES_Matriculados_Posg", periodoParameter);
        }
    
        public virtual ObjectResult<SNIES_Matriculados_Preg_Result> SNIES_Matriculados_Preg(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNIES_Matriculados_Preg_Result>("SNIES_Matriculados_Preg", periodoParameter);
        }
    
        public virtual ObjectResult<SNIES_Participantes_Posg_Result> SNIES_Participantes_Posg(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNIES_Participantes_Posg_Result>("SNIES_Participantes_Posg", periodoParameter);
        }
    
        public virtual ObjectResult<SNIES_Participantes_Preg_Result> SNIES_Participantes_Preg(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("periodo", periodo) :
                new ObjectParameter("periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SNIES_Participantes_Preg_Result>("SNIES_Participantes_Preg", periodoParameter);
        }
    }
}
